############## application properties ###############
spring:
  application:
    name: mssc-brewery
  thymeleaf:
    cache: false
    prefix: classpath:/templates          
############## Log properties ###############
logging:
  level:
    org.springframework.security: DEBUG
    com.woowrale.architecture.microservice: DEBUG
############## Server properties ###############
server:
  port: 8081
  tomcat:
    basedir: target/tomcat/
  servlet:
    contextPath: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
############## Project properties ###############
mssc:
  apiPath: /api/v1/beer/
  apiHost: http://localhost:8081