apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontapp-nginx
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /frontapp
            pathType: Prefix
            backend:
              service:
                name: frontapp
                port:
                  number: 8080