apiVersion: v1
kind: Service
metadata:
  name: frontapp
  labels:
    app: frontapp
spec:
  type: ClusterIP
  selector:
    app: frontapp
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP