apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsvcx
  labels:
    app: productsvcx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productsvcx
  template:
    metadata:
      labels:
        app: productsvcx
    spec:
      containers:
        - name: productsvcx
          image: cadbcraftsman/productsvcx:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8080
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: /productsvcx              
            #- name: SPRING_CLOUD_CONFIG_URI
            #  value: http://config-service
            #- name: SPRING_PROFILES_ACTIVE
            #  value: dev
            #- name: SPRING_DATASOURCE_URL
            #  value: jdbc:h2:file:./target/data/products-db
