apiVersion: v1
kind: Service
metadata:
  name: productsvcx
  labels:
    app: productsvcx
spec:
  type: ClusterIP
  selector:
    app: productsvcx
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP   