apiVersion: v1
kind: Service
metadata:
  name: springboot-frontapp
  namespace: default
  labels:
    app: springboot-frontapp
spec:
  type: NodePort
  selector:
    app: springboot-frontapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-frontapp
  namespace: kube-system
spec:
  type: ExternalName
  externalName: springboot-frontapp.default.svc.cluster.local
