apiVersion: v1
kind: Service
metadata:
  name: catalogsvc
  labels:
    app: catalogsvc
spec:
  type: ClusterIP
  selector:
    app: catalogsvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9080